#ifndef BYTECODE_OPCODE_H
#define BYTECODE_OPCODE_H

enum bytecode_opcode
{
    BYTECODE_OPCODE_HALT           = 0x00,

    BYTECODE_OPCODE_MOVU_REG_IMM   = 0x01,
    BYTECODE_OPCODE_MOVI_REG_IMM   = 0x02,
    BYTECODE_OPCODE_MOVF_REG_IMM   = 0x03,
    BYTECODE_OPCODE_MOV_REG_REG    = 0x04,

    BYTECODE_OPCODE_PUSHU_IMM      = 0x10,
    BYTECODE_OPCODE_PUSHI_IMM      = 0x11,
    BYTECODE_OPCODE_PUSHF_IMM      = 0x12,
    BYTECODE_OPCODE_PUSH_REG       = 0x13,
    BYTECODE_OPCODE_POP_REG        = 0x14,

    BYTECODE_OPCODE_ADDU_REG_IMM   = 0x30,
    BYTECODE_OPCODE_ADDI_REG_IMM   = 0x31,
    BYTECODE_OPCODE_ADDF_REG_IMM   = 0x32,
    BYTECODE_OPCODE_ADD_REG_REG    = 0x33,

    BYTECODE_OPCODE_COUNT          = 0xFF
};

#endif
